# site properties and page defaults
title: Sharpe Lab
# subtitle: by the Sharpe Lab
description: Hello and welcome to the Sharpe Lab website!
header: images/strain.jpg
# footer: images/background.jpg
proofer: false

# hide title text in navigation (since logo.svg contains "Sharplab")
show-title: false

# site social media and other links
links:
  email: aaron.sharpe@stanford.edu
  orcid: 0000-0002-4260-8546
  google-scholar: 7LPtqEsAAAAJ&hl
  github: sharpelab
  # twitter: YourLabHandle
  # youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member

collections:
  # generate page for each member
  members:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
